version: "3.8"
services:
  backend:
    container_name: loto_servidor
    build: 
      context: ./back-end-loto-app
    ports:
      - ${PORT_BACK}:${PORT_BACK}
    volumes:
      - ./back-end-loto-app:/usr/src/app
    env_file: ./back-end-loto-app/.env
  frontend:
    image: node:18-alpine
    container_name: loto_client
    entrypoint: /bin/sh
    ports:
      - ${PORT_FRONT}:${PORT_FRONT}
    working_dir: /usr/src/app
    volumes:
     - type: bind
       source: ./
       target: /usr/src/app
    tty: true
    env_file: ./front-end-loto-app/.env
