version: "3.8"
services:
  backend:
    container_name: loto_servidor
    build: 
      context: ./back-end-loto-app
    ports:
      - ${PORT_BACK}:${PORT_BACK}
    volumes:
      - ./back-end-loto-app:/usr/src/app
    env_file: ./back-end-loto-app/.env
  frontend:
    container_name: loto_client
    build: 
      context: ./front-end-loto-app
    ports:
      - ${PORT_FRONT}:${PORT_FRONT}
    volumes:
      - ./front-end-loto-app:/usr/src/app
    env_file: ./front-end-loto-app/.env